### PR TITLE
[Feat] add the API `assign_values`

### PR DESCRIPTION
**Pull request by rhdong**
- Add `check_evict_strategy` for `assign`

### CODE REVIEW

**Comment by evanrang** [comment]
Hi, you hive renamed this API to `assign_values`, why not rename the assign scores API to `assign_scores` as well ?

**Comment by rhdong** [comment]
> Hi, you hive renamed this API to `assign_values`, why not rename the assign scores API to `assign_scores` as well ?

Yes, I agree, considering the compatibility with the old versions, maybe I can add an alias for it instead of renaming it. How do you think about it?

**Comment by evanrang** [comment]
> > Hi, you hive renamed this API to `assign_values`, why not rename the assign scores API to `assign_scores` as well ?
> 
> Yes, I agree, considering the compatibility with the old versions, maybe I can add an alias for it instead of renaming it. How do you think about it?

perfect 👍

**Review by evanrang — APPROVED** [review]

**Pull request merged**
