### PR TITLE
[bug] Attempt to fix GPU/CPU race condition of the memory pool test.

### PR DESCRIPTION
**Pull request by bashimao**
Tries to fix: https://github.com/NVIDIA-Merlin/HierarchicalKV/issues/143

### CODE REVIEW

**Comment by bashimao** [comment]
@rhdong @jiashuy

I have investigated the code. Assuming my understanding of the bug is correct, there is no problem with the existing logic in the actual memory pool code. It is only the test that makes a wrong assumption. In the 4th test, we use streams to allow asynchronous buffer borrowing. This is great because we keep reusing memory (almost) without blocking.

What happens is that the test fails if the GPU/driver has such a high latency that the CUDA event appended to the stream is not yet triggered. Unfortunately, on my test machine this is almost never the case. So, I can only hardly reproduce the situation. What we see is a classic race condition. I restructured the test to force stable conditions between individual tests. I think I covered all cases. But please let me know if it fails again.

This is good news, because based on current knowledge, customers are not affected. It is only the test that makes wrong assumptions.

**Comment by rhdong** [comment]
> @rhdong @jiashuy
> 
> I have investigated the code. Assuming my understanding of the bug is correct, there is no problem with the existing logic in the actual memory pool code. It is only the test that makes a wrong assumption. In the 4th test, we use streams to allow asynchronous buffer borrowing. This is great because we keep reusing memory (almost) without blocking.
> 
> What happens is that the test fails if the GPU/driver has such a high latency that the CUDA event appended to the stream is not yet triggered. Unfortunately, on my test machine this is almost never the case. So, I can only hardly reproduce the situation. What we see is a classic race condition. I restructured the test to force stable conditions between individual tests. I think I covered all cases. But please let me know if it fails again.
> 
> This is good news, because based on current knowledge, customers are not affected. It is only the test that makes wrong assumptions.

Hi @bashimao, Thank you for your work. And to @jiashuy, Could you pick the commit to your branch for temporary testing?

**Comment by jiashuy** [comment]
> > @rhdong @jiashuy
> > I have investigated the code. Assuming my understanding of the bug is correct, there is no problem with the existing logic in the actual memory pool code. It is only the test that makes a wrong assumption. In the 4th test, we use streams to allow asynchronous buffer borrowing. This is great because we keep reusing memory (almost) without blocking.
> > What happens is that the test fails if the GPU/driver has such a high latency that the CUDA event appended to the stream is not yet triggered. Unfortunately, on my test machine this is almost never the case. So, I can only hardly reproduce the situation. What we see is a classic race condition. I restructured the test to force stable conditions between individual tests. I think I covered all cases. But please let me know if it fails again.
> > This is good news, because based on current knowledge, customers are not affected. It is only the test that makes wrong assumptions.
> 
> Hi @bashimao, Thank you for your work. And to @jiashuy, Could you pick the commit to your branch for temporary testing?

Yes, no problem

**Review by rhdong — APPROVED** [review]
LGTM

**Pull request merged**
