### PR TITLE
[Refactor] optimize the accum by new algorithm

### PR DESCRIPTION
**Pull request by rhdong**
- By the way, remove the `min_score` and `min_pos` from the Bucket struct, which reduces the memory consumption by 33%.

### CODE REVIEW

**Review by Lifann — APPROVED** [review]
LGTM

**Comment by rhdong** [comment]
From the [CI backend](https://prod.blsm.nvidia.com/sw-gpu-hugectr-ci-master/job/merlin-kv-ci/215/consoleFull), we can see the CI testing has been passed.

**Pull request merged**
